version: "3"

services:
  mysql:
    container_name: ddd_forum_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${DDD_FORUM_DB_DEV_DB_NAME}
      - MYSQL_USER=${DDD_FORUM_DB_USER}
      - MYSQL_PASSWORD=${DDD_FORUM_DB_PASS}

  adminer:  
    container_name: ddd_forum_adminer
    image: adminer
    depends_on:
      - mysql
    expose:
      - 8080
    ports:
      - 8080:8080

  redis:
    container_name: ddd_forum_redis
    image: redis:latest
    expose:
      - 6379
    ports:  
      - 6379:6379

  app:
    container_name: ddd_forum_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    expose:
      - 3000
      - 5001
    ports: 
        - 3000:3000
        - 5001:5001
 