common:
  request_headers:
    Accept: application/json
    Content-Type: application/json
local:
  api_base_url: http://localhost:5001/api/v1
  log_level: debug
prod:
  api_base_url: http://localhost:5001/api/v1
  log_level: debug
  time_zone: utc